window.NOCTURNE_CONFIG = {
    visuals: {
        arrival: {
            key: "arrival",
            label: "First Fire",
            title: "Charred shellfish, smoked stock, bitter citrus.",
            url: "https://images.unsplash.com/photo-1697532275880-144e78f0aa24?auto=format&fit=crop&w=2200&q=70",
            alt: "Restaurant exterior at night with glowing signage",
            credit: {
                source: "Unsplash",
                license: "Unsplash License",
                photographer: "WEI JIAHENG",
                photographer_url: "https://unsplash.com/@blueskymegumi",
                photo_url: "https://unsplash.com/photos/an-asian-restaurant-at-night-with-neon-signs-0TXQ72yf_bA",
                license_url: "https://unsplash.com/license",
            },
        },
        menu: {
            key: "menu",
            label: "Course Sequence",
            title: "Tasting course under low light.",
            url: "https://images.pexels.com/photos/28705621/pexels-photo-28705621.jpeg?auto=compress&cs=tinysrgb&w=2200",
            alt: "Plated gourmet dish with sauce and herb garnish",
            credit: {
                source: "Pexels",
                license: "Pexels License",
                photographer: "Filipp Romanovski",
                photographer_url: "https://www.pexels.com/@filipp-romanovski/",
                photo_url: "https://www.pexels.com/photo/gourmet-fine-dining-plate-with-sauce-and-herbs-28705621/",
                license_url: "https://www.pexels.com/license/",
            },
        },
        room: {
            key: "room",
            label: "The Salon",
            title: "Dark room, warm tables, quieter corners.",
            url: "https://images.pexels.com/photos/15627000/pexels-photo-15627000.jpeg?auto=compress&cs=tinysrgb&w=2200",
            alt: "Dark modern restaurant interior with warm lighting",
            credit: {
                source: "Pexels",
                license: "Pexels License",
                photographer: "miniperde",
                photographer_url: "https://www.pexels.com/@miniperde/",
                photo_url: "https://www.pexels.com/photo/dark-modern-interior-of-a-restaurant-15627000/",
                license_url: "https://www.pexels.com/license/",
            },
        },
        journal: {
            key: "journal",
            label: "Kitchen Notes",
            title: "Short notes from the pass, not filler.",
            url: "https://images.unsplash.com/photo-1767700358285-fcfff3619cc4?auto=format&fit=crop&w=2200&q=70",
            alt: "Writing notes in a notebook at a table",
            credit: {
                source: "Unsplash",
                license: "Unsplash License",
                photographer: "Hoi An and Da Nang Photographer",
                photographer_url: "https://unsplash.com/@hoianphotographer",
                photo_url: "https://unsplash.com/photos/man-writing-in-notebook-at-a-table-8wNsPjF6jls",
                license_url: "https://unsplash.com/license",
            },
        },
        reserve: {
            key: "reserve",
            label: "Reserve",
            title: "Leave the night and guest count.",
            url: "https://images.unsplash.com/photo-1697532275880-144e78f0aa24?auto=format&fit=crop&w=2200&q=70",
            alt: "Restaurant exterior at night with glowing signage",
            credit: {
                source: "Unsplash",
                license: "Unsplash License",
                photographer: "WEI JIAHENG",
                photographer_url: "https://unsplash.com/@blueskymegumi",
                photo_url: "https://unsplash.com/photos/an-asian-restaurant-at-night-with-neon-signs-0TXQ72yf_bA",
                license_url: "https://unsplash.com/license",
            },
        },
    },
    reservation: {
        provider: "demo",
        endpoint: "",
        accessKey: "",
        fromName: "Nocturne Table",
    },
    feeds: {
        notesUrl: "./data/today-notes.json",
        socialUrl: "./data/social-feed.json",
    },
};
